import {spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,copyFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {gzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
const root=fileURLToPath(new URL('../',import.meta.url));
const result=spawnSync(process.execPath,['scripts/build-browser-platform.mjs'],{cwd:root+'source',stdio:'inherit',windowsHide:true});
if(result.error)throw result.error;if(result.status)process.exit(result.status);
const report=JSON.parse(readFileSync(root+'source/artifacts/decomp/browser-platform-build.json'));
const bytes=readFileSync(root+'source/artifacts/decomp/browser-platform.wasm');
if(createHash('sha256').update(bytes).digest('hex')!==report.sha256)throw new Error('Build output mismatch');
mkdirSync(root+'site/vendor',{recursive:true});
writeFileSync(root+'site/vendor/th10-game.wasm',bytes);
writeFileSync(root+'site/vendor/th10-game.wasm.gz',gzipSync(bytes,{level:9}));
copyFileSync(root+'source/artifacts/decomp/browser-platform-build.json',root+'source/build-report.json');
const manifest=JSON.parse(readFileSync(root+'site/manifest.json'));
manifest.execution={kind:'cpp-game-logic',module:'th10-game.wasm',bytes:bytes.length,sha256:report.sha256,sourceSha256:report.sourceSha256};
writeFileSync(root+'site/manifest.json',JSON.stringify(manifest,null,2)+'\n');
const release=JSON.parse(readFileSync(root+'release.json'));release.manifest=manifest;release.sourceFiles=report.sourceFiles.length;
writeFileSync(root+'release.json',JSON.stringify(release,null,2)+'\n');
console.log('Updated site/vendor, manifest and source/build-report.json.');
